/*
 * Education Frameworks
 * Copyright © 2015-2017 Origin Studio Inc.
 *
 */

#pragma once

#include <NetEasy/CommonHeader.h>
#include "Enums.h"

const INT iDB_FIELD_NAME_LEN = 30;

const INT iWEB_RESPONSE_BUFFER_LEN = 1024;

const INT iCONSOLE_BUFFER_LEN = 2048;
const INT iCONSOLE_MESSAGE_LINE = 100;

const INT iANIMATOR_IDLE_LEN = 2;
const INT iANIMATOR_ATTACK_LEN = 2;
const INT iANIMATOR_MOVE_LEN = 9;
const INT iANIMATOR_DIED_LEN = 14;

const INT iANIMATOR_ZOMBIE_MOTION_LENGTH[ZOMBIE_STATE_COUNT] = { 1, 10, 8, iANIMATOR_DIED_LEN }; //{ ZOMBIE_STATE_IDLE, ZOMBIE_STATE_INFEST, ZOMBIE_STATE_MOVE, ZOMBIE_STATE_DIE };

const INT iPLAYER_MOVE_DISTANCE = 2;

const INT iANIMATOR_IDLE_LATENCY = 30;
const INT iANIMATOR_ATTACK_LATENCY = 5;
const INT iANIMATOR_MOVE_LATENCY = 3;
const INT iANIMATOR_DIED_LATENCY = 50;

const INT iANIMATOR_ZOMBIE_MOTION_LATENCY[ZOMBIE_STATE_COUNT] = { 1, 1, 1, iANIMATOR_DIED_LATENCY }; //{ ZOMBIE_STATE_IDLE, ZOMBIE_STATE_INFEST, ZOMBIE_STATE_MOVE, ZOMBIE_STATE_DIE };

const FLOAT fCOLLITION_MAP_TRANSPARENCY = 0.2f;

const INT iDROP_ITEM_WIDTH = 6;
const INT iDROP_ITEM_HEIGHT = 6;